server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: http://localhost:8082/
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: http://localhost:8087/
          predicates:
            - Path=/ead-course/**
  application:
    name: ead-api-gateway