server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://ead-authuser-service
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://ead-course-service
          predicates:
            - Path=/ead-course/**
        - id: notification-service
          uri: lb://ead-notification-service
          predicates:
            - Path=/ead-notification/**
  application:
    name: ead-api-gateway

ead:
  service-registry:
    username: serviceregistryclient
    password: 'secretead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost